services:
  postgres:
    image: postgres:14
    container_name: central_doacoes
    environment:
      POSTGRES_DB: central_doacoes
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5433:5432"
    networks:
      - meu_network

networks:
  meu_network:
    driver: bridge


